# Generated by Django 5.2.4 on 2025-07-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='marqueemessage',
            name='afficher',
            field=models.BooleanField(default=False),
        ),
    ]
